import './globals.css'
import { Inter, Mulish, Raleway, Oswald } from 'next/font/google'
import clsx from 'clsx'

// const inter = Inter({ subsets: ['latin'] })
const oswald = Oswald({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] })
const mulish = Mulish({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={oswald.className}>{children}</body> */}
      <body className={clsx([raleway.className, oswald.className, mulish.className])}>{children}</body>
    </html>
  )
}
